export default {
  "login": "Esteban Pajares",
  "id": 2,
  "node_id": "MDQ6VXNlcjI=",
  "avatar_url": "https://avatars.githubusercontent.com/u/63526566?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/defunkt",
  "html_url": "https://github.com/defunkt",
  "followers_url": "https://api.github.com/users/defunkt/followers",
  "following_url": "https://api.github.com/users/defunkt/following{/other_user}"
,
  "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
  "organizations_url": "https://api.github.com/users/defunkt/orgs",
  "repos_url": "https://api.github.com/users/defunkt/repos",
  "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
  "received_events_url": "https://api.github.com/users/defunkt/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Esteban",
  "company": null,
  "blog": "https://github.com/EstebanPajares",
  "location": 'Lima - Perú',
  "email": null,
  "hireable": null,
  "bio": "🍔 Software Engineer",
  "twitter_username": 'EstebanPajares',
  "public_repos": 107,
  "public_gists": 273,
  "followers": 21596,
  "following": 211,
  "created_at": "2007-10-20T05:24:19Z",
  "updated_at": "2023-03-03T08:18:32Z"
}
